CREATE TABLE {{HISTORY_TABLE}}
(
  id         INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id    BIGINT(20) UNSIGNED NOT NULL,
  old_value  DECIMAL(10,2) UNSIGNED NULL,
  new_value  DECIMAL(10,2) UNSIGNED NULL,
  meta_key   VARCHAR(100) NULL,
  origin     ENUM( {{ORIGINS}} ) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX      meta_key_index (meta_key),
  CONSTRAINT {{HISTORY_CONSTRAINT_TABLE}} FOREIGN KEY (post_id) REFERENCES {{POSTS_TABLE}}(ID) ON DELETE CASCADE
);