CREATE TABLE {{PRODUCTS_TABLE}}
(
  id         BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_id BIGINT(20) UNSIGNED NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT {{PRODUCTS_CONSTRAINT_TABLE}} FOREIGN KEY (product_id) REFERENCES {{POSTS_TABLE}}(ID) ON DELETE CASCADE
  );